Thu Nov 29 2018 14:08:08 GMT+0530 (India Standard Time) - SyntaxError: Unexpected string in JSON at position 34
    at JSON.parse (<anonymous>)
    at parse (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Thu Nov 29 2018 14:08:15 GMT+0530 (India Standard Time) - Error: Could not connect to database
    at mongoose.connect.then.catch (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\utilities\connection.js:50:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:11:51 GMT+0530 (India Standard Time) - Error: Could not connect to database
    at mongoose.connect.then.catch (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\utilities\connection.js:52:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:28:15 GMT+0530 (India Standard Time) - Error: No transaction details found
    at dbLayer.getTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:29:01 GMT+0530 (India Standard Time) - Error: No transaction details found
    at dbLayer.getTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:29:19 GMT+0530 (India Standard Time) - Error: No transaction details found
    at dbLayer.getTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:31:46 GMT+0530 (India Standard Time) - TypeError: Cannot read property 'transactions' of null
    at collection.findOne.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\model\account.js:44:25)
Thu Nov 29 2018 14:33:09 GMT+0530 (India Standard Time) - Error: No transaction details found
    at dbLayer.getTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:35:23)
Thu Nov 29 2018 14:34:03 GMT+0530 (India Standard Time) - Error: No transaction details found
    at dbLayer.getTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu Nov 29 2018 14:35:15 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:35:49 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:37:59 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:40:12 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:40:31 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:42:02 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 14:59:00 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: username_1 dup key: { : "guru@gmail.com" }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:06:15 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:11:53 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:13:29 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:17:10 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:43:42 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:44:53 GMT+0530 (India Standard Time) - Error: Invalid PAN number
    at Object.validator.validatePAN (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\utilities\validator.js:13:19)
    at Object.service.createAccount (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:43:15)
    at routing.post (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\routes\routing.js:50:13)
    at Layer.handle [as handle_request] (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\express\lib\router\index.js:335:12)
Thu Nov 29 2018 15:45:00 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:47:07 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:49:25 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:49:41 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:50:02 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:50:15 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:53:24 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 15:53:41 GMT+0530 (India Standard Time) - MongoError: E11000 duplicate key error collection: ExpressWalletDB.Account index: transactions.tid_1 dup key: { : null }
    at Function.create (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.insert (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb\lib\operations\collection_ops.js:844:39)
    at C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
Thu Nov 29 2018 16:07:48 GMT+0530 (India Standard Time) - Error: User already exists
    at dbLayer.getUser.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:46:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 14:31:15 GMT+0530 (India Standard Time) - ReferenceError: response is not defined
    at collection.updateOne.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\model\account.js:84:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 14:32:03 GMT+0530 (India Standard Time) - Error: No transaction details found or operation failed
    at dbLayer.deleteTransaction.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:80:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 14:33:12 GMT+0530 (India Standard Time) - Error: No transaction details found or operation failed
    at dbLayer.deleteTransaction.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:80:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 15:58:22 GMT+0530 (India Standard Time) - Error: Transaction details not updated
    at dbLayer.updateTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:69:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 15:59:28 GMT+0530 (India Standard Time) - Error: Transaction details not updated
    at dbLayer.updateTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:69:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri Nov 30 2018 15:59:58 GMT+0530 (India Standard Time) - Error: Transaction details not updated
    at dbLayer.updateTransactions.then (C:\Users\gurumoorthyg.g\Desktop\ExpressWalletUpdatedDB\src\service\account.js:69:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Wed May 01 2019 - ReferenceError: dobj is not defined
    at routing.get (C:\Users\plint_000\Desktop\DeviceProject\src\routes\routing.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:335:12)
Wed May 01 2019 - ReferenceError: dobj is not defined
    at routing.get (C:\Users\plint_000\Desktop\DeviceProject\src\routes\routing.js:41:5)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\DeviceProject\node_modules\express\lib\router\index.js:335:12)
Wed May 01 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Wed May 01 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - TypeError: data.length is not a function
    at collection2.find.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\model\device.js:61:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - Error: device not allocated
    at dbLayer.allocateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:35:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - TypeError: service1.updateSystem is not a function
    at routing.get (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:77:14)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
Thu May 02 2019 - TypeError: service1.updateSystem is not a function
    at routing.get (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:77:14)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
Thu May 02 2019 - TypeError: dbLayer.updateSystem is not a function
    at Object.service.updateSystem (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:69:20)
    at routing.get (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:77:14)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
Thu May 02 2019 - Error: update failed
    at dbLayer.updateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:74:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Thu May 02 2019 - ObjectParameterError: Parameter "obj" to Document() must be an object, got johndoe@gmail.com
    at new ObjectParameterError (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\error\objectParameter.js:25:11)
    at model.Document (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:71:11)
    at model.Model (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\model.js:95:12)
    at new model (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\model.js:4567:13)
    at toExecute.push.callback (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\model.js:2893:22)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\async\internal\parallel.js:31:39
    at eachOfArrayLike (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\async\eachOf.js:65:9)
    at exports.default (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\async\eachOf.js:9:5)
    at _parallel (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\async\internal\parallel.js:30:5)
    at parallelLimit (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\async\parallel.js:88:26)
    at utils.promiseOrCallback.cb (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\model.js:2908:5)
    at Promise (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\utils.js:270:5)
    at new Promise (<anonymous>)
    at Object.promiseOrCallback (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\utils.js:269:10)
    at Function.create (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\model.js:2864:16)
    at collection3.getCollection.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\model\device.js:210:28)
Fri May 03 2019 - TypeError: dbLayer.getUser is not a function
    at Object.service.validateLogin (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\account.js:13:20)
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:28:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
Fri May 03 2019 - TypeError: dbLayer.getUser is not a function
    at Object.service.validateLogin (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\account.js:13:20)
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:28:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
Fri May 03 2019 - TypeError: dbLayer.getUser is not a function
    at Object.service.validateLogin (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\account.js:13:20)
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:28:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
Fri May 03 2019 - TypeError: dbLayer.getUser is not a function
    at Object.service.validateLogin (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\account.js:13:20)
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:30:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
Fri May 03 2019 - TypeError: dbLayer.getUser is not a function
    at Object.service.validateLogin (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\account.js:13:20)
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:30:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
Fri May 03 2019 - Error: User does not exist
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: User does not exist
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: User does not exist
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: User does not exist
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: User does not exist
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: Incorrect password
    at dbLayer.getUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:22:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - TypeError: service.createRequest is not a function
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:103:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at requestLogger (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\utilities\requestlogger.js:9:5)
Fri May 03 2019 - TypeError: service.createRequest is not a function
    at routing.post (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\routes\routing.js:103:13)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\express\lib\router\index.js:275:10)
    at requestLogger (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\utilities\requestlogger.js:9:5)
Fri May 03 2019 - ValidationError: Request validation failed: username: Path `username` is required.
    at new ValidationError (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2256:32)
    at p.doValidate.skipSchemaValidators (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2105:17)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\schematype.js:978:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Fri May 03 2019 - Error: creating record failed
    at dbLayer.createRequest.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:102:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - ValidationError: Request validation failed: username: Path `username` is required.
    at new ValidationError (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2256:32)
    at p.doValidate.skipSchemaValidators (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2105:17)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\schematype.js:978:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Fri May 03 2019 - ValidationError: Request validation failed: username: Path `username` is required.
    at new ValidationError (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2256:32)
    at p.doValidate.skipSchemaValidators (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2105:17)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\schematype.js:978:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Fri May 03 2019 - ValidationError: Request validation failed: username: Path `username` is required.
    at new ValidationError (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2256:32)
    at p.doValidate.skipSchemaValidators (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\document.js:2105:17)
    at C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\node_modules\mongoose\lib\schematype.js:978:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
Fri May 03 2019 - ReferenceError: allocateSystem is not defined
    at collection3.deleteOne.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\model\device.js:255:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: no data found
    at dbLayer.acceptreq.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:144:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - ReferenceError: allocateSystem is not defined
    at collection3.deleteOne.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\model\device.js:255:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - ReferenceError: allocateSystem is not defined
    at collection3.deleteOne.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\model\device.js:256:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: no data found
    at dbLayer.acceptreq.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:144:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: update failed
    at dbLayer.updateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:76:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:89:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:89:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: could not find user
    at dbLayer.searchUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:50:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: update failed
    at dbLayer.updateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:76:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: could not find user
    at dbLayer.searchUser.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:50:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: deleting failed
    at dbLayer.deleteAllocation.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:90:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: update failed
    at dbLayer.updateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:76:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Fri May 03 2019 - Error: update failed
    at dbLayer.updateSystem.then (C:\Users\plint_000\Desktop\NEWPROJECT\DeviceProject\src\service\device.js:76:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
